name: Xodium CI/CD - Build App

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup-deno
        name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: stable

      - id: build-app
        name: Build App
        run: |
          deno task build
          deno compile --output xodium-org --include _fresh -A _fresh/compiled-entry.js

      - id: upload-artifact
        name: Upload Build Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v6.0.0
        with:
          path: xodium-org