name: Illyrion CI/CD
run-name: "Illyrion CI/CD"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy_to_github_pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: setup_node
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - id: package_script
        name: Package Script
        run: npm run build

      - id: remove_sass_ts
        name: Remove SASS & TS Folder
        run: rm -rf src/assets/scss/ src/assets/ts/

      - id: setup_pages
        name: Setup Pages
        uses: actions/configure-pages@main

      - id: upload_artifact
        name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: "./src"

      - id: deploy_to_github_pages
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
